In [ ]:
import env

frame = env.Game(True, False)
frame.run_game()  

pygame 2.2.0 (SDL 2.32.54, Python 3.8.20)
Hello from the pygame community. https://www.pygame.org/contribute.html
未检测到已有模型！将重新训练
use gpu!
```````````````````````````````````````````````````````
episode:1
tensor([[ 0.0202, -0.0196,  0.0418,  0.0498]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
epsilon:1.0
！随机选择！
action:2 || food(29, 11) || head(15, 15)
```````````````````````````````````````````````````````
episode:1
tensor([[ 0.0201, -0.0201,  0.0414,  0.0501]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
epsilon:1.0
！随机选择！
action:0 || food(29, 11) || head(15, 14)
```````````````````````````````````````````````````````
episode:1
tensor([[ 0.0202, -0.0198,  0.0418,  0.0505]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
epsilon:1.0
！随机选择！
action:1 || food(29, 11) || head(14, 14)
```````````````````````````````````````````````````````
episode:1
tensor([[ 0.0203, -0.0197,  0.0420,  0.0502]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
epsilon:1.0
！随机选择！
action:3 ||

In [2]:
b = [1, 2]
a = [b, 2]
c = a
c[0][1] = 3
print(a)
print(c)

[[1, 3], 2]
[[1, 3], 2]


In [4]:
import copy
import numpy as np
state = [[1,2],
         [3,4]
        ]
rotated_state = np.rot90(state, 1)
print(rotated_state)
print(state)

[[2 4]
 [1 3]]
[[1, 2], [3, 4]]
