In [4]:
import train_env

#episodes  save show spilson max_guide_num
frame = train_env.ENV(4000, 100, 10000, 0.2, -1) 
frame.main(False)  

成功加载已有Q模型及参数！
成功加载已有目标模型！
use gpu!
Episode: 1
length: 1  maxLength:1 action:{1: 38, 2: 67, 0: 7}
Episode: 2
length: 1  maxLength:1 action:{1: 44, 2: 61, 0: 8}
Episode: 3
length: 2  maxLength:1 action:{1: 135, 2: 136, 0: 20}
Episode: 4
length: 1  maxLength:2 action:{1: 306, 2: 257, 0: 35}
Episode: 5
length: 1  maxLength:2 action:{1: 55, 2: 63, 0: 7}
Episode: 6
length: 1  maxLength:2 action:{0: 2, 1: 16, 2: 9}
Episode: 7
length: 1  maxLength:2 action:{1: 771, 2: 794, 0: 105}
Episode: 8
length: 1  maxLength:2 action:{0: 2, 1: 27, 2: 13}
Episode: 9
length: 1  maxLength:2 action:{1: 39, 2: 33, 0: 7}
Episode: 10
length: 1  maxLength:2 action:{1: 157, 0: 28, 2: 210}
Episode: 11
length: 1  maxLength:2 action:{1: 293, 2: 255, 0: 38}
Episode: 12
length: 2  maxLength:2 action:{1: 63, 2: 23, 0: 8}
Episode: 13
length: 1  maxLength:2 action:{1: 65, 0: 8, 2: 87}
Episode: 14
length: 1  maxLength:2 action:{2: 15, 0: 2, 1: 1}
Episode: 15
length: 1  maxLength:2 action:{1: 49, 0: 8, 2: 66}
Episode: 16
len

In [5]:
import numpy as np
import copy
a = np.zeros((2,3))
def change(b):
    a = b.copy()
    a[0][0] = 4
    print(a)
change(a)
print(a)

[[4. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
import copy
import numpy as np
state = [[1,2],
         [3,4]
        ]
rotated_state = np.rot90(state, 1)
print(rotated_state)
print(state)

[[2 4]
 [1 3]]
[[1, 2], [3, 4]]


In [1]:
import random
import torch
states = [[0.1061, 0.1190, 0.0694, 0.0808]]

value = torch.FloatTensor(states).unsqueeze(0).unsqueeze(0)
v = value[0][0][0]
print(max_value)

max_indices = []
max_v = max(v)
for i in range(4):
    if v[i] == max_v:
        max_indices.append(i)

res = random.choice(max_indices)
print(res)

NameError: name 'max_value' is not defined

In [14]:
import numpy as np
import model
net = model.Net(15, 3)
Q = model.DQN(net)
a = np.zeros((15, 15))
a = torch.FloatTensor(a).unsqueeze(0).unsqueeze(0)
res = Q.value(a)
print(res)
print(res[0][1])
# print(max(res[0]))
# print(res.max(1)[0])

tensor([[-0.0566, -0.2286,  0.1981]], grad_fn=<AddmmBackward0>)
tensor(-0.2286, grad_fn=<SelectBackward0>)


In [6]:
print(max[-0.09415875375270844, -0.07439233362674713, -0.06203056126832962, -0.09894663095474243])

TypeError: 'builtin_function_or_method' object is not subscriptable