In [2]:
import train_env

#                    episodes  save  show  spilson  max_guide_num
frame = train_env.ENV(4000, 100, 1000000, 0.2, -1) 
frame.main(False)  

成功加载已有Q模型及参数！
成功加载已有目标模型！
use gpu!
Episode: 1
length: 1  maxLength:1 action:{1: 37, 2: 10, 0: 2}
Episode: 2
length: 1  maxLength:1 action:{1: 26, 2: 8}
Episode: 3
length: 1  maxLength:1 action:{1: 76, 2: 28, 0: 4}
Episode: 4
length: 2  maxLength:1 action:{2: 11, 1: 3, 0: 2}
Episode: 5
length: 1  maxLength:2 action:{1: 3, 2: 15, 0: 1}
Episode: 6
length: 1  maxLength:2 action:{1: 15, 2: 3}
Episode: 7
length: 1  maxLength:2 action:{1: 50, 2: 62, 0: 4}
Episode: 8
length: 1  maxLength:2 action:{1: 11, 0: 2}
Episode: 9
length: 1  maxLength:2 action:{1: 31, 2: 49, 0: 4}
Episode: 10
length: 1  maxLength:2 action:{1: 31, 0: 7, 2: 49}
Episode: 11
length: 1  maxLength:2 action:{2: 11, 0: 1}
Episode: 12
length: 2  maxLength:2 action:{1: 27, 2: 18, 0: 1}
Episode: 13
length: 1  maxLength:2 action:{2: 17, 1: 1}
Episode: 14
length: 1  maxLength:2 action:{2: 12, 0: 1}
Episode: 15
length: 1  maxLength:2 action:{1: 17, 2: 4, 0: 2}
Episode: 16
length: 1  maxLength:2 action:{1: 1, 2: 16, 0: 1}
Episode: 17


In [5]:
import numpy as np
import copy
a = np.zeros((2,3))
def change(b):
    a = b.copy()
    a[0][0] = 4
    print(a)
change(a)
print(a)

[[4. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
import copy
import numpy as np
state = [[1,2],
         [3,4]
        ]
rotated_state = np.rot90(state, 1)
print(rotated_state)
print(state)

[[2 4]
 [1 3]]
[[1, 2], [3, 4]]


In [1]:
import random
import torch
states = [[0.1061, 0.1190, 0.0694, 0.0808]]

value = torch.FloatTensor(states).unsqueeze(0).unsqueeze(0)
v = value[0][0][0]
print(max_value)

max_indices = []
max_v = max(v)
for i in range(4):
    if v[i] == max_v:
        max_indices.append(i)

res = random.choice(max_indices)
print(res)

NameError: name 'max_value' is not defined

In [10]:
import numpy as np
import model
import torch
net = model.Net(15, 3)
Q = model.DQN(net)
a = np.zeros((15, 15))
a = torch.FloatTensor(a)
res = Q.value(a)
print(max(res))
print(max(res).item())
print(max(res.item()))
print(max(res))
# print(res[0][1])
# print(max(res[0]))
# print(res.max(1)[0])

tensor(0.1505, grad_fn=<UnbindBackward0>)
0.15050488710403442


RuntimeError: a Tensor with 3 elements cannot be converted to Scalar

In [6]:
print(max[-0.09415875375270844, -0.07439233362674713, -0.06203056126832962, -0.09894663095474243])

TypeError: 'builtin_function_or_method' object is not subscriptable